apiVersion: apps/v1
kind: Deployment
metadata:
  name: monster-deploy
  labels:
    app: full-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: gehadmohmaed1/monsterinc
        env:
        - name: DB_NAME
          value: "django"
        - name: DB_USER
          value: "django"
        - name: DB_PASS
          value: "django123"
        - name: HOST_IP
          value: "mysql-0.mysql"
        ports:
        - containerPort: 8000
        

---
apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django
  ports:
    - port: 8000
      targetPort: 8000
  type: LoadBalancer